import type { ArticleCategory } from '../types';

/**
 * Prompt-driven templates.
 *
 * Each TemplateSection is a single "card" the user can pick from the prompt
 * picker modal — heading becomes an H2 in the article and the prompt
 * becomes an italicized question beneath it.
 *
 * Articles do NOT auto-populate with these anymore. Use the prompt picker
 * inside the editor to insert the ones you want.
 */
export interface TemplateSection {
  heading: string;
  prompt: string;
}

export const TEMPLATES: Record<ArticleCategory, TemplateSection[]> = {
  species: [
    { heading: 'Overview',                  prompt: 'A short, evocative description of this species. What is the first thing you notice about them?' },
    { heading: 'Average Height',            prompt: 'How tall do adults stand? Note any sexual dimorphism, regional variation, or sub-types.' },
    { heading: 'Average Weight',            prompt: 'Typical mass at maturity.' },
    { heading: 'Lifespan',                  prompt: 'How long do they live? What does old age look like for them?' },
    { heading: 'Anatomy',                   prompt: 'Skeletal structure, organs, unique features (gills, wings, multiple hearts…).' },
    { heading: 'Senses',                    prompt: 'Which senses are dominant? Anything humans cannot perceive?' },
    { heading: 'Diet',                      prompt: 'What do they eat? How do they get it?' },
    { heading: 'Habitat',                   prompt: 'Where are they found in the world? What environments do they thrive in?' },
    { heading: 'Reproduction',              prompt: 'How do they bring new life into the world? How often?' },
    { heading: 'Juvenile Stage',            prompt: 'What are their young like? How long until they reach maturity?' },
    { heading: 'Communication',             prompt: 'Language, song, scent, body posture, telepathy — how do they signal each other?' },
    { heading: 'Social Structure',          prompt: 'Pack, hive, solitary, kin-bands, kingdoms? Who leads?' },
    { heading: 'Society & Culture',         prompt: 'How do they organize themselves? What do they believe?' },
    { heading: 'Mating & Bonding',          prompt: 'Courtship, pair-bonding, rituals around joining.' },
    { heading: 'Traditions & Rites',        prompt: 'Coming-of-age, mourning, harvest, hunt — what do they observe?' },
    { heading: 'Art & Expression',          prompt: 'How does this species make beauty? Music, carving, dance, story?' },
    { heading: 'Religion & Belief',         prompt: 'What do they hold sacred? What do they fear in the dark?' },
    { heading: 'Technology Level',          prompt: 'Stone, bronze, magical, post-industrial? What tools do they carry?' },
    { heading: 'Weapons & Warfare',         prompt: 'How do they fight, if they fight?' },
    { heading: 'Relations with Other Species', prompt: 'Allies, prey, predators, partners, rivals.' },
    { heading: 'Notable Individuals',       prompt: 'Famous members of this species.' },
    { heading: 'History & Origin',          prompt: 'Where did they come from? Are they native or alien to this world?' },
    { heading: 'Decline & Threats',         prompt: 'What is killing them, or could?' },
    { heading: 'Naming Conventions',        prompt: 'How are individuals named? What do names mean?' },
    { heading: 'Taboos & Forbidden',        prompt: 'What is never done? Why?' },
  ],

  character: [
    { heading: 'Quick Take',           prompt: 'In one paragraph: who is this person?' },
    { heading: 'Appearance',           prompt: 'Height, build, hair, eyes, scars, clothing.' },
    { heading: 'First Impression',     prompt: 'What strangers think after thirty seconds in their presence.' },
    { heading: 'Personality',          prompt: 'Three honest words. Then explain each.' },
    { heading: 'Manner of Speech',     prompt: 'How do they talk? Catchphrases? Accent? What do they avoid saying?' },
    { heading: 'Goals',                prompt: 'What do they want? What do they NEED?' },
    { heading: 'Fears',                prompt: 'What would break them?' },
    { heading: 'Weakness',             prompt: 'The thing about them that is going to cause trouble.' },
    { heading: 'Strength',             prompt: 'The thing they can be counted on for.' },
    { heading: 'Background',           prompt: 'Where did they grow up? Who shaped them?' },
    { heading: 'Family',               prompt: 'Living, dead, estranged, chosen.' },
    { heading: 'Skills & Abilities',   prompt: 'What can they do that most cannot?' },
    { heading: 'Magic',                prompt: 'Do they wield it? If so, how?' },
    { heading: 'Weapon of Choice',     prompt: 'If they fight, what do they reach for first?' },
    { heading: 'Faith & Belief',       prompt: 'What do they pray to, if anything?' },
    { heading: 'Possessions',          prompt: 'What do they carry? What matters?' },
    { heading: 'Relationships',        prompt: 'Family, allies, enemies, lovers.' },
    { heading: 'Voice & Mannerisms',   prompt: 'Tics, habits, gestures — what do they always do?' },
    { heading: 'Secrets',              prompt: 'What do they hide?' },
    { heading: 'Greatest Regret',      prompt: 'The thing they would undo if they could.' },
    { heading: 'Pivotal Moment',       prompt: 'The day that made them who they are.' },
    { heading: 'How They Die',         prompt: 'If you know — write it down. If not — guess.' },
    { heading: 'Theme Song / Vibe',    prompt: 'What music plays when they walk into a room?' },
  ],

  place: [
    { heading: 'Description',          prompt: 'What does it look, sound, smell like?' },
    { heading: 'First Impression',     prompt: 'A traveler arriving for the first time — what do they notice?' },
    { heading: 'Location',             prompt: 'Where in the world is it?' },
    { heading: 'Climate & Seasons',    prompt: 'What is the weather like across the year?' },
    { heading: 'Inhabitants',          prompt: 'Who lives here?' },
    { heading: 'Architecture',         prompt: 'What is built here, and from what materials?' },
    { heading: 'Streets & Layout',     prompt: 'How does one move through this place? Grid, organic, layered?' },
    { heading: 'Economy',              prompt: 'How do people make a living here?' },
    { heading: 'Trade & Resources',    prompt: 'What flows in and out?' },
    { heading: 'Food',                 prompt: 'What is served here? What do locals miss when they leave?' },
    { heading: 'Sounds & Smells',      prompt: 'Close your eyes — what does the air carry?' },
    { heading: 'Notable Sites',        prompt: 'Landmarks within this place.' },
    { heading: 'Inns & Gatherings',    prompt: 'Where do people meet to drink, argue, plot?' },
    { heading: 'Hidden Places',        prompt: 'The corners outsiders never see.' },
    { heading: 'Conflicts',            prompt: 'What tensions simmer here?' },
    { heading: 'Government',           prompt: 'Who rules, and how lightly do they hold the reins?' },
    { heading: 'Crime',                prompt: 'Is there a guild? A code? Whom does it serve?' },
    { heading: 'Festivals',            prompt: 'When do the streets fill with light?' },
    { heading: 'Founding',             prompt: 'Who built it, when, and why?' },
    { heading: 'History',              prompt: 'Founded when, by whom, and why?' },
    { heading: 'Local Lore',           prompt: 'Stories the children are told.' },
    { heading: 'Reputation',           prompt: 'What do outsiders say about this place?' },
  ],

  country: [
    { heading: 'Overview',             prompt: 'A short description of the country.' },
    { heading: 'Government',           prompt: 'Who rules and how?' },
    { heading: 'Capital',              prompt: 'Seat of power.' },
    { heading: 'Population',           prompt: 'How many, which species, where do they live?' },
    { heading: 'Demographics',         prompt: 'Urban vs rural, age, wealth, faith.' },
    { heading: 'Geography',            prompt: 'Borders, climate, terrain.' },
    { heading: 'Major Cities',         prompt: 'Beyond the capital — where else does power gather?' },
    { heading: 'Economy',              prompt: 'Major exports, currency, trade partners.' },
    { heading: 'Currency',             prompt: 'What backs it? What is it called?' },
    { heading: 'Military',             prompt: 'Standing forces, special units.' },
    { heading: 'Justice & Law',        prompt: 'Who judges? What are the punishments?' },
    { heading: 'Religion',             prompt: 'Dominant faiths.' },
    { heading: 'Education',            prompt: 'Who learns, what, and from whom?' },
    { heading: 'Culture & Identity',   prompt: 'What does it mean to call yourself a citizen here?' },
    { heading: 'Cuisine',              prompt: 'A meal a foreigner would remember forever.' },
    { heading: 'Holidays',             prompt: 'Days the country pauses.' },
    { heading: 'Language',             prompt: 'Official, common, dying, forbidden.' },
    { heading: 'Foreign Relations',    prompt: 'Allies, rivals, neutral parties.' },
    { heading: 'Current Tension',      prompt: 'What is the present-day crisis?' },
    { heading: 'History',              prompt: 'Founding, wars, golden ages, dark times.' },
    { heading: 'Famous Citizens',      prompt: 'Names schoolchildren learn.' },
    { heading: 'Secret Shame',         prompt: 'What is hidden from official histories?' },
  ],

  language: [
    { heading: 'Overview',             prompt: 'Who speaks it? Where?' },
    { heading: 'Sound & Feel',         prompt: 'Is it harsh, lyrical, clipped? Compare to a real language.' },
    { heading: 'Syllable Structure',   prompt: 'e.g. CV, CVC, CCV. Example syllables.' },
    { heading: 'Phonology',            prompt: 'Inventory of consonants and vowels.' },
    { heading: 'Stress & Rhythm',      prompt: 'Where does the emphasis fall?' },
    { heading: 'Grammar Rules',        prompt: 'Word order, tenses, cases, gender.' },
    { heading: 'Pronouns',             prompt: 'How does this language refer to people?' },
    { heading: 'Numbers',              prompt: 'How are they counted? Base ten, twelve, twenty?' },
    { heading: 'Script',               prompt: 'Written form. Direction. Alphabet or logographic?' },
    { heading: 'Punctuation',          prompt: 'How do they mark pause, question, end?' },
    { heading: 'Core Vocabulary',      prompt: 'Sun, water, fire, family, death — the words a child learns first.' },
    { heading: 'Vocabulary',           prompt: 'Core words to seed your dictionary.' },
    { heading: 'Common Phrases',       prompt: 'Greetings, oaths, insults, prayers.' },
    { heading: 'Idioms',               prompt: 'Sayings that lose their meaning in translation.' },
    { heading: 'Names',                prompt: 'How are people named? What do common names mean?' },
    { heading: 'Place Names',          prompt: 'Conventions for naming towns, rivers, mountains.' },
    { heading: 'Dialects',             prompt: 'Regional variants and their flavor.' },
    { heading: 'Slang',                prompt: 'How does the young generation twist it?' },
    { heading: 'Forbidden Words',      prompt: 'What cannot be said aloud, and why?' },
    { heading: 'History',              prompt: 'Where did it come from? How has it changed?' },
    { heading: 'Speakers Today',       prompt: 'Is it thriving, fading, or extinct?' },
  ],

  item: [
    { heading: 'Description',          prompt: 'What does it look like in hand?' },
    { heading: 'Materials',            prompt: 'What is it made of? Anything rare or magical?' },
    { heading: 'Origin',               prompt: 'Who made it, when, why?' },
    { heading: 'Properties',           prompt: 'Magical or mundane abilities.' },
    { heading: 'Activation',           prompt: 'How is it used? Words, gestures, blood?' },
    { heading: 'Cost of Use',          prompt: 'What does the item ask of its wielder?' },
    { heading: 'Weight & Feel',        prompt: 'What does it weigh? Warm or cold to the touch?' },
    { heading: 'Current Owner',        prompt: 'Where is it now?' },
    { heading: 'Previous Owners',      prompt: 'A chain of names, each a story.' },
    { heading: 'History',              prompt: 'Who has held it across the ages?' },
    { heading: 'Stolen / Lost',        prompt: 'Has it ever vanished? Who searched for it?' },
    { heading: 'Legends',              prompt: 'Stories people tell about it.' },
    { heading: 'True Name',            prompt: 'Does it have one? Who knows it?' },
    { heading: 'Inscription',          prompt: 'What is written on it, if anything?' },
    { heading: 'Value',                prompt: 'In coin, in lives, in souls.' },
    { heading: 'How to Destroy It',    prompt: 'What would it take to unmake this object?' },
  ],

  geography: [
    { heading: 'Description',          prompt: 'What sort of land is this?' },
    { heading: 'Terrain',              prompt: 'Elevation, dominant features, hazards.' },
    { heading: 'Climate',              prompt: 'Weather patterns and seasons.' },
    { heading: 'Sky',                  prompt: 'What does the sky look like here? Stars, moons, auroras?' },
    { heading: 'Water',                prompt: 'Rivers, lakes, oceans, springs.' },
    { heading: 'Flora',                prompt: 'What grows here?' },
    { heading: 'Fauna',                prompt: 'What lives here naturally?' },
    { heading: 'Resources',            prompt: 'What can be harvested?' },
    { heading: 'Dangers',              prompt: 'Natural hazards.' },
    { heading: 'Sacred Sites',         prompt: 'Places treated with reverence.' },
    { heading: 'Cursed Sites',         prompt: 'Places people refuse to go.' },
    { heading: 'Settlements',          prompt: 'Where do people gather here, if at all?' },
    { heading: 'Travel Routes',        prompt: 'How does one move through this land?' },
    { heading: 'Seasons of Change',    prompt: 'How does this place transform across the year?' },
    { heading: 'Lore',                 prompt: 'Stories tied to this place.' },
  ],

  material: [
    { heading: 'Description',          prompt: 'What is it? Where is it found?' },
    { heading: 'Appearance',           prompt: 'Color, texture, sheen.' },
    { heading: 'Properties',           prompt: 'Hardness, density, behavior, magical resonance.' },
    { heading: 'Source',               prompt: 'Where in the world does it come from?' },
    { heading: 'Extraction',           prompt: 'How is it gathered or made?' },
    { heading: 'Refining',             prompt: 'What does it take to make it usable?' },
    { heading: 'Uses',                 prompt: 'What is it crafted into?' },
    { heading: 'Limitations',          prompt: 'What does it not do well?' },
    { heading: 'Rarity & Value',       prompt: 'Common, rare, legendary?' },
    { heading: 'Trade',                prompt: 'Who buys, who sells, who hoards?' },
    { heading: 'Wars Over It',         prompt: 'Has anyone ever fought for control of it?' },
    { heading: 'Lore',                 prompt: 'Cultural significance.' },
    { heading: 'Substitutes',          prompt: 'When you cannot get this material, what else might serve?' },
  ],

  military: [
    { heading: 'Overview',             prompt: 'What is this unit and who fields it?' },
    { heading: 'Composition',          prompt: 'Size, ranks, species mix.' },
    { heading: 'Recruitment',          prompt: 'Who joins, willingly or otherwise?' },
    { heading: 'Training',             prompt: 'How are they made into soldiers?' },
    { heading: 'Equipment',            prompt: 'Standard gear.' },
    { heading: 'Special Equipment',    prompt: 'Anything unique or legendary.' },
    { heading: 'Tactics',              prompt: 'How do they fight?' },
    { heading: 'Doctrine',             prompt: 'What do they believe makes a good soldier?' },
    { heading: 'Insignia & Colors',    prompt: 'How are they recognized in the field?' },
    { heading: 'Notable Engagements',  prompt: 'Battles, campaigns.' },
    { heading: 'Defeats',              prompt: 'When did they lose, and what was lost with them?' },
    { heading: 'Leadership',           prompt: 'Current commanders.' },
    { heading: 'Loyalty',              prompt: 'To whom? Country, leader, gold, idea?' },
    { heading: 'Reputation',           prompt: 'What do enemies say about them?' },
  ],

  myth: [
    { heading: 'The Story',            prompt: 'Tell the myth as a believer would.' },
    { heading: 'Who Tells It',         prompt: 'Which culture, which generation, around which fire?' },
    { heading: 'When Told',            prompt: 'Festival, funeral, lullaby, warning?' },
    { heading: 'Key Figures',          prompt: 'Who are the actors in this myth?' },
    { heading: 'Symbolism',            prompt: 'What does it really mean to its tellers?' },
    { heading: 'Variants',             prompt: 'How does the story shift across regions?' },
    { heading: 'Older Version',        prompt: 'What did the myth look like a thousand years ago?' },
    { heading: 'Heretical Reading',    prompt: 'How might an outsider or skeptic interpret it?' },
    { heading: 'Cultural Impact',      prompt: 'What customs trace back to this story?' },
    { heading: 'Truth Beneath',        prompt: 'What actually happened, if anything?' },
  ],

  natural_law: [
    { heading: 'The Law',              prompt: 'State the rule of your world plainly.' },
    { heading: 'How It Manifests',     prompt: 'What does it look like to a witness?' },
    { heading: 'Consequences',         prompt: 'What changes because of this law?' },
    { heading: 'Edge Cases',           prompt: 'When does it bend or break?' },
    { heading: 'Discovery',            prompt: 'How was it learned?' },
    { heading: 'First Recording',      prompt: 'Who first wrote it down? Can they be trusted?' },
    { heading: 'Exploitation',         prompt: 'Who has used this and how?' },
    { heading: 'Religious Reading',    prompt: 'How do faiths explain it?' },
    { heading: 'Scientific Reading',   prompt: 'How do scholars explain it?' },
    { heading: 'Tension With Other Laws', prompt: 'Where does this law contradict others?' },
  ],

  organization: [
    { heading: 'Overview',             prompt: 'Mission and identity in one breath.' },
    { heading: 'Structure',            prompt: 'Hierarchy, ranks, councils.' },
    { heading: 'Headquarters',         prompt: 'Where do they meet, plot, decide?' },
    { heading: 'Membership',           prompt: 'Who joins? How?' },
    { heading: 'Initiation',           prompt: 'What does it take to be made one of them?' },
    { heading: 'Code & Oath',          prompt: 'What do members swear to?' },
    { heading: 'Resources',            prompt: 'Wealth, holdings, influence.' },
    { heading: 'Symbols & Regalia',    prompt: 'How are they marked? Robes, sigils, scars?' },
    { heading: 'Allies & Enemies',     prompt: 'Who stands with them, who against?' },
    { heading: 'Rivals Within',        prompt: 'Internal factions, ambitions, betrayals.' },
    { heading: 'Methods',              prompt: 'How do they pursue their goals?' },
    { heading: 'History',              prompt: 'Founding, schisms, milestones.' },
    { heading: 'Current Leader',       prompt: 'Who sits at the top now, and how long do they have left?' },
    { heading: 'Secrets',              prompt: 'What outsiders do not know.' },
  ],

  profession: [
    { heading: 'Overview',             prompt: 'What does someone in this trade actually do?' },
    { heading: 'A Typical Day',        prompt: 'Walk through it from dawn to dusk.' },
    { heading: 'Training',             prompt: 'How does one become one?' },
    { heading: 'Tools of the Trade',   prompt: 'Equipment, materials, gear.' },
    { heading: 'Apprenticeship',       prompt: 'How long does it take to be considered competent?' },
    { heading: 'Master\'s Mark',       prompt: 'How is true mastery recognized?' },
    { heading: 'Pay',                  prompt: 'How well does this profession live?' },
    { heading: 'Status',               prompt: 'Are they respected? Reviled? Anonymous?' },
    { heading: 'Guilds & Unions',      prompt: 'Who organizes them, if anyone?' },
    { heading: 'Hazards',              prompt: 'What does this trade cost the body or mind?' },
    { heading: 'Notable Practitioners',prompt: 'Famous examples.' },
    { heading: 'Common Myths',         prompt: 'What do outsiders wrongly assume about this work?' },
  ],

  religion: [
    { heading: 'Core Belief',          prompt: 'What does this religion teach about the world?' },
    { heading: 'Origin Story',         prompt: 'How did this faith begin?' },
    { heading: 'Pantheon',             prompt: 'Deities, spirits, sacred figures.' },
    { heading: 'Cosmology',            prompt: 'Where do souls go? How was the world made?' },
    { heading: 'Practices',            prompt: 'Daily rites, festivals, taboos.' },
    { heading: 'Holy Days',            prompt: 'When does the faith pause everything to remember?' },
    { heading: 'Clergy',               prompt: 'Who leads, how are they trained?' },
    { heading: 'Holy Sites',           prompt: 'Where do followers gather?' },
    { heading: 'Pilgrimage',           prompt: 'Where do the devout walk to?' },
    { heading: 'Scripture',            prompt: 'Sacred texts and oral tradition.' },
    { heading: 'Hymns & Prayers',      prompt: 'A line everyone knows.' },
    { heading: 'Vestments',            prompt: 'What do clergy wear, and why?' },
    { heading: 'Funerary Rites',       prompt: 'How are the dead returned to whatever comes next?' },
    { heading: 'Initiation',           prompt: 'How does one become a follower?' },
    { heading: 'Schisms',              prompt: 'Internal divisions and heresies.' },
    { heading: 'Heresies',             prompt: 'The forbidden readings still whispered.' },
    { heading: 'Miracles & Wonders',   prompt: 'Specific recorded events the faithful point to.' },
    { heading: 'Relations',            prompt: 'Other faiths it tolerates or hates.' },
    { heading: 'Persecutions',         prompt: 'When has this faith been suppressed?' },
    { heading: 'Modern Trends',        prompt: 'Is it rising, falling, splintering, hardening?' },
  ],

  title: [
    { heading: 'Meaning',              prompt: 'What does this title signify?' },
    { heading: 'Pronunciation',        prompt: 'How is it spoken in formal address?' },
    { heading: 'Granted By',           prompt: 'Who can bestow it?' },
    { heading: 'Requirements',         prompt: 'Birth, deed, blood, blade?' },
    { heading: 'Ceremony',             prompt: 'How is the title conferred?' },
    { heading: 'Duties',               prompt: 'Responsibilities of the bearer.' },
    { heading: 'Privileges',           prompt: 'Powers and perks.' },
    { heading: 'Regalia',              prompt: 'Items and dress that mark the holder.' },
    { heading: 'Loss of Title',        prompt: 'How can it be taken back, or shed?' },
    { heading: 'Notable Bearers',      prompt: 'Past and present holders.' },
    { heading: 'Common Misuse',        prompt: 'Where is this title claimed without authority?' },
  ],

  spell: [
    { heading: 'Effect',               prompt: 'What does it do?' },
    { heading: 'Visible Manifestation',prompt: 'What does a witness see, hear, feel?' },
    { heading: 'Components',           prompt: 'Words, gestures, materials.' },
    { heading: 'Time to Cast',         prompt: 'An instant, a breath, an hour?' },
    { heading: 'Cost',                 prompt: 'What does casting take from the caster?' },
    { heading: 'Range & Duration',     prompt: 'How far, how long.' },
    { heading: 'Targeting',            prompt: 'A single subject, an area, a thing?' },
    { heading: 'Counters',             prompt: 'How is it resisted or unmade?' },
    { heading: 'Failure Modes',        prompt: 'What happens when the cast fails?' },
    { heading: 'Variants',             prompt: 'Greater, lesser, or twisted forms.' },
    { heading: 'Schools',              prompt: 'Which traditions claim this spell as theirs?' },
    { heading: 'Lore',                 prompt: 'Who created it? Who guards it?' },
    { heading: 'Forbidden Use',        prompt: 'When is this spell a crime?' },
  ],

  tradition: [
    { heading: 'The Practice',         prompt: 'Describe the tradition as an outsider would witness it.' },
    { heading: 'When Observed',        prompt: 'Season, occasion, life event.' },
    { heading: 'Participants',         prompt: 'Who takes part? Who is excluded?' },
    { heading: 'Symbols',              prompt: 'Objects, words, foods involved.' },
    { heading: 'Music & Sound',        prompt: 'What is sung or played?' },
    { heading: 'Food & Drink',         prompt: 'What is served? Anything specific to the day?' },
    { heading: 'Dress',                prompt: 'What do participants wear?' },
    { heading: 'Origin',               prompt: 'Why does this tradition exist?' },
    { heading: 'Modern Variants',      prompt: 'How has it changed?' },
    { heading: 'Regional Differences', prompt: 'How does each place put its own mark on it?' },
    { heading: 'Tensions',             prompt: 'Who disagrees with how this is observed?' },
    { heading: 'When Broken',          prompt: 'What happens if the tradition is ignored or refused?' },
  ],

  vehicle: [
    { heading: 'Description',          prompt: 'Appearance and feel.' },
    { heading: 'Propulsion',           prompt: 'Sails, magic, beast, engine?' },
    { heading: 'Crew',                 prompt: 'How many, what roles?' },
    { heading: 'Capacity',             prompt: 'Cargo and passengers.' },
    { heading: 'Speed & Range',        prompt: 'How fast, how far without resupply?' },
    { heading: 'Armament',             prompt: 'Weapons or defenses.' },
    { heading: 'Quirks',               prompt: 'Every vehicle has them. What are this one\'s?' },
    { heading: 'Construction',         prompt: 'Materials, builders, where it was made.' },
    { heading: 'Cost',                 prompt: 'To buy, to maintain, to crew.' },
    { heading: 'Notable Examples',     prompt: 'Famous ships, mounts, machines.' },
    { heading: 'Captains & Riders',    prompt: 'Who commands it, now and across history?' },
    { heading: 'Lore',                 prompt: 'Stories told around the fire about this craft.' },
  ],

  conflict: [
    { heading: 'Summary',              prompt: 'In a paragraph: who, what, when, why.' },
    { heading: 'Sides',                prompt: 'Factions and their goals.' },
    { heading: 'Allegiances',          prompt: 'Who allies with whom, and how stable are those bonds?' },
    { heading: 'Causes',               prompt: 'What set this in motion?' },
    { heading: 'Inciting Incident',    prompt: 'The single moment everything pivoted on.' },
    { heading: 'Course of Events',     prompt: 'Key battles, turning points.' },
    { heading: 'Atrocities',           prompt: 'What will be remembered with shame?' },
    { heading: 'Heroes',               prompt: 'Names that will be sung.' },
    { heading: 'Villains',             prompt: 'Names that will be cursed.' },
    { heading: 'Casualties',           prompt: 'Human, material, cultural costs.' },
    { heading: 'Outcome',              prompt: 'How did it end? Or did it?' },
    { heading: 'Peace Terms',          prompt: 'What was agreed, and what was left unsaid?' },
    { heading: 'Aftermath',            prompt: 'What changed because of it?' },
    { heading: 'Long Shadows',         prompt: 'How are descendants still living with this?' },
  ],

  deity: [
    { heading: 'Domain',               prompt: 'What aspects of existence do they govern?' },
    { heading: 'Appearance',           prompt: 'How do they manifest, if they do?' },
    { heading: 'Sacred Form',          prompt: 'The image in temples and on relics.' },
    { heading: 'Symbol',               prompt: 'The mark of their worship.' },
    { heading: 'Sacred Animal / Plant',prompt: 'A creature or growth associated with them.' },
    { heading: 'Sacred Color',         prompt: 'What hue is theirs?' },
    { heading: 'Sacred Number',        prompt: 'Recurring count in their rites.' },
    { heading: 'Followers',            prompt: 'Who venerates them?' },
    { heading: 'Tenets',               prompt: 'What do they ask of mortals?' },
    { heading: 'Forbidden Acts',       prompt: 'What earns their wrath?' },
    { heading: 'Common Prayers',       prompt: 'A line every devotee knows.' },
    { heading: 'Offerings',            prompt: 'What is given to them?' },
    { heading: 'Foes',                 prompt: 'Rival gods, ancient enemies.' },
    { heading: 'Allies',               prompt: 'Which other gods walk beside them?' },
    { heading: 'Origin',               prompt: 'Where did they come from?' },
    { heading: 'Endings & Prophecies', prompt: 'Are they immortal, or is an ending foretold?' },
  ],

  history: [
    { heading: 'Era',                  prompt: 'When did this take place?' },
    { heading: 'Setting',              prompt: 'Where in the world did this unfold?' },
    { heading: 'What Happened',        prompt: 'Tell the story.' },
    { heading: 'Key Figures',          prompt: 'Who was there?' },
    { heading: 'Witnesses',            prompt: 'Who saw it and lived to tell?' },
    { heading: 'Lost Voices',          prompt: 'Whose account was never recorded?' },
    { heading: 'Causes',               prompt: 'What led to this moment?' },
    { heading: 'Consequences',         prompt: 'How did the world change?' },
    { heading: 'Mythologized Version', prompt: 'How does popular memory misremember it?' },
    { heading: 'Counterfactual',       prompt: 'What if it had gone the other way?' },
    { heading: 'Sources',              prompt: 'Who recorded this, and can they be trusted?' },
  ],

  magic_system: [
    { heading: 'The Source',           prompt: 'Where does magic come from in this world?' },
    { heading: 'Access',               prompt: 'Who can use it? How is it learned?' },
    { heading: 'Cost',                 prompt: 'What does magic take from those who wield it?' },
    { heading: 'Rules',                prompt: 'The hard laws. What CANNOT magic do?' },
    { heading: 'Soft Limits',          prompt: 'What can be done, but at great cost?' },
    { heading: 'Branches',             prompt: 'Schools, traditions, elemental affinities.' },
    { heading: 'Components',           prompt: 'Words, gestures, materials, focuses.' },
    { heading: 'Tools',                prompt: 'Wands, runes, focuses, components.' },
    { heading: 'Visible Manifestation',prompt: 'When a spell is cast, what does the world see?' },
    { heading: 'Detection',            prompt: 'Can mundane people tell when magic is at work?' },
    { heading: 'Counter-magic',        prompt: 'Can it be resisted, dispelled, or twisted back?' },
    { heading: 'Risks of Misuse',      prompt: 'What happens when magic goes wrong?' },
    { heading: 'Society',              prompt: 'How does the world treat mages?' },
    { heading: 'Politics of Power',    prompt: 'Who controls magical instruction, and why?' },
    { heading: 'Famous Practitioners', prompt: 'Names that shaped the art.' },
    { heading: 'Forbidden Practices',  prompt: 'What is outlawed, and what punishments follow?' },
    { heading: 'History',              prompt: 'When did magic appear? Has it changed?' },
    { heading: 'Future',               prompt: 'Is magic waxing or waning? Why?' },
  ],

  note: [
    { heading: 'Notes',                prompt: 'Open scratchpad. Write whatever comes.' },
    { heading: 'Question',             prompt: 'What are you trying to figure out?' },
    { heading: 'Loose Threads',        prompt: 'What needs to be tied back into the world later?' },
  ],
};

/** Get all prompts for a category, padding with universal ones if too few. */
export function getPrompts(category: ArticleCategory): TemplateSection[] {
  return TEMPLATES[category] ?? TEMPLATES.note;
}
