import type { ArticleCategory } from '../types';

/** Prompt-driven templates. Each item is a heading and question/blank text. */
export interface TemplateSection {
  heading: string;
  prompt: string;
}

export const TEMPLATES: Record<ArticleCategory, TemplateSection[]> = {
  species: [
    { heading: 'Overview',           prompt: 'A short, evocative description of this species. What is the first thing you notice about them?' },
    { heading: 'Average Height',     prompt: 'How tall do adults stand? Note any sexual dimorphism or sub-types.' },
    { heading: 'Lifespan',           prompt: 'How long do they live? What does old age look like for them?' },
    { heading: 'Anatomy',            prompt: 'Skeletal structure, organs, unique features (gills, wings, multiple hearts…)' },
    { heading: 'Habitat',            prompt: 'Where are they found in the world? What environments do they thrive in?' },
    { heading: 'Diet & Hunting',     prompt: 'What do they eat? How do they get it?' },
    { heading: 'Reproduction',       prompt: 'How do they bring new life into the world? How often?' },
    { heading: 'Society & Culture',  prompt: 'How do they organize themselves? What do they believe?' },
    { heading: 'Notable Individuals',prompt: 'Famous members of this species.' },
    { heading: 'History & Origin',   prompt: 'Where did they come from? Are they native or alien to this world?' },
  ],
  character: [
    { heading: 'Quick Take',         prompt: 'In one paragraph: who is this person?' },
    { heading: 'Appearance',         prompt: 'Height, build, hair, eyes, scars, clothing.' },
    { heading: 'Personality',        prompt: 'Three honest words. Then explain each.' },
    { heading: 'Goals',              prompt: 'What do they want? What do they NEED?' },
    { heading: 'Fears',              prompt: 'What would break them?' },
    { heading: 'Background',         prompt: 'Where did they grow up? Who shaped them?' },
    { heading: 'Skills & Abilities', prompt: 'What can they do that most cannot?' },
    { heading: 'Relationships',      prompt: 'Family, allies, enemies, lovers.' },
    { heading: 'Voice',              prompt: 'How do they talk? Catchphrases? Accent?' },
    { heading: 'Secrets',            prompt: 'What do they hide?' },
  ],
  place: [
    { heading: 'Description',        prompt: 'What does it look, sound, smell like?' },
    { heading: 'Location',           prompt: 'Where in the world is it?' },
    { heading: 'Inhabitants',        prompt: 'Who lives here?' },
    { heading: 'History',            prompt: 'Founded when, by whom, and why?' },
    { heading: 'Notable Sites',      prompt: 'Landmarks within this place.' },
    { heading: 'Conflicts',          prompt: 'What tensions simmer here?' },
    { heading: 'Trade & Economy',    prompt: 'What flows in and out?' },
  ],
  country: [
    { heading: 'Overview',           prompt: 'A short description of the country.' },
    { heading: 'Government',         prompt: 'Who rules and how?' },
    { heading: 'Capital',            prompt: 'Seat of power.' },
    { heading: 'Population',         prompt: 'How many, which species, where do they live?' },
    { heading: 'Geography',          prompt: 'Borders, climate, terrain.' },
    { heading: 'Economy',            prompt: 'Major exports, currency, trade partners.' },
    { heading: 'Military',           prompt: 'Standing forces, special units.' },
    { heading: 'Religion',           prompt: 'Dominant faiths.' },
    { heading: 'History',            prompt: 'Founding, wars, golden ages, dark times.' },
    { heading: 'Relations',          prompt: 'Allies, rivals, neutral parties.' },
  ],
  language: [
    { heading: 'Overview',           prompt: 'Who speaks it? Where?' },
    { heading: 'Sound & Feel',       prompt: 'Is it harsh, lyrical, clipped? Compare to a real language.' },
    { heading: 'Syllable Structure', prompt: 'e.g. CV, CVC, CCV. Example syllables.' },
    { heading: 'Phonology',          prompt: 'Inventory of consonants and vowels.' },
    { heading: 'Grammar Rules',      prompt: 'Word order, tenses, cases, gender.' },
    { heading: 'Script',             prompt: 'Written form. Direction. Alphabet or logographic?' },
    { heading: 'Vocabulary',         prompt: 'Core words to seed your dictionary.' },
    { heading: 'Common Phrases',     prompt: 'Greetings, oaths, insults, prayers.' },
    { heading: 'Dialects',           prompt: 'Regional variants and their flavor.' },
    { heading: 'History',            prompt: 'Where did it come from? How has it changed?' },
  ],
  item: [
    { heading: 'Description',        prompt: 'What does it look like in hand?' },
    { heading: 'Origin',             prompt: 'Who made it, when, why?' },
    { heading: 'Properties',         prompt: 'Magical or mundane abilities.' },
    { heading: 'Current Owner',      prompt: 'Where is it now?' },
    { heading: 'History',            prompt: 'Who has held it across the ages?' },
    { heading: 'Legends',            prompt: 'Stories people tell about it.' },
  ],
  geography: [
    { heading: 'Description',        prompt: 'What sort of land is this?' },
    { heading: 'Climate',            prompt: 'Weather patterns and seasons.' },
    { heading: 'Flora & Fauna',      prompt: 'What lives here naturally?' },
    { heading: 'Resources',          prompt: 'What can be harvested?' },
    { heading: 'Dangers',            prompt: 'Natural hazards.' },
    { heading: 'Lore',               prompt: 'Stories tied to this place.' },
  ],
  material: [
    { heading: 'Description',        prompt: 'What is it? Where is it found?' },
    { heading: 'Properties',         prompt: 'Hardness, density, behavior, magical resonance.' },
    { heading: 'Extraction',         prompt: 'How is it gathered or made?' },
    { heading: 'Uses',               prompt: 'What is it crafted into?' },
    { heading: 'Rarity & Value',     prompt: 'Common, rare, legendary?' },
    { heading: 'Lore',               prompt: 'Cultural significance.' },
  ],
  military: [
    { heading: 'Overview',           prompt: 'What is this unit and who fields it?' },
    { heading: 'Composition',        prompt: 'Size, ranks, species mix.' },
    { heading: 'Equipment',          prompt: 'Standard gear.' },
    { heading: 'Tactics',            prompt: 'How do they fight?' },
    { heading: 'Notable Engagements',prompt: 'Battles, campaigns.' },
    { heading: 'Leadership',         prompt: 'Current commanders.' },
  ],
  myth: [
    { heading: 'The Story',          prompt: 'Tell the myth as a believer would.' },
    { heading: 'Who Tells It',       prompt: 'Which culture, which generation, around which fire?' },
    { heading: 'Symbolism',          prompt: 'What does it really mean to its tellers?' },
    { heading: 'Variants',           prompt: 'How does the story shift across regions?' },
    { heading: 'Truth Beneath',      prompt: 'What actually happened, if anything?' },
  ],
  natural_law: [
    { heading: 'The Law',            prompt: 'State the rule of your world plainly.' },
    { heading: 'Consequences',       prompt: 'What changes because of this law?' },
    { heading: 'Edge Cases',         prompt: 'When does it bend or break?' },
    { heading: 'Discovery',          prompt: 'How was it learned?' },
    { heading: 'Exploitation',       prompt: 'Who has used this and how?' },
  ],
  organization: [
    { heading: 'Overview',           prompt: 'Mission and identity in one breath.' },
    { heading: 'Structure',          prompt: 'Hierarchy, ranks, councils.' },
    { heading: 'Membership',         prompt: 'Who joins? How?' },
    { heading: 'Resources',          prompt: 'Wealth, holdings, influence.' },
    { heading: 'Allies & Enemies',   prompt: 'Who stands with them, who against?' },
    { heading: 'History',            prompt: 'Founding, schisms, milestones.' },
    { heading: 'Secrets',            prompt: 'What outsiders do not know.' },
  ],
  profession: [
    { heading: 'Overview',           prompt: 'What does someone in this trade actually do?' },
    { heading: 'Training',           prompt: 'How does one become one?' },
    { heading: 'Tools of the Trade', prompt: 'Equipment, materials, gear.' },
    { heading: 'Status',             prompt: 'Are they respected? Reviled? Anonymous?' },
    { heading: 'Notable Practitioners', prompt: 'Famous examples.' },
  ],
  religion: [
    { heading: 'Core Belief',        prompt: 'What does this religion teach about the world?' },
    { heading: 'Pantheon',           prompt: 'Deities, spirits, sacred figures.' },
    { heading: 'Practices',          prompt: 'Daily rites, festivals, taboos.' },
    { heading: 'Clergy',             prompt: 'Who leads, how are they trained?' },
    { heading: 'Holy Sites',         prompt: 'Where do followers gather?' },
    { heading: 'Scripture',          prompt: 'Sacred texts and oral tradition.' },
    { heading: 'Schisms',            prompt: 'Internal divisions and heresies.' },
    { heading: 'Relations',          prompt: 'Other faiths it tolerates or hates.' },
  ],
  title: [
    { heading: 'Meaning',            prompt: 'What does this title signify?' },
    { heading: 'Granted By',         prompt: 'Who can bestow it?' },
    { heading: 'Duties',             prompt: 'Responsibilities of the bearer.' },
    { heading: 'Privileges',         prompt: 'Powers and perks.' },
    { heading: 'Notable Bearers',    prompt: 'Past and present holders.' },
  ],
  spell: [
    { heading: 'Effect',             prompt: 'What does it do?' },
    { heading: 'Components',         prompt: 'Words, gestures, materials.' },
    { heading: 'Cost',               prompt: 'What does casting take from the caster?' },
    { heading: 'Range & Duration',   prompt: 'How far, how long.' },
    { heading: 'Counters',           prompt: 'How is it resisted or unmade?' },
    { heading: 'Lore',               prompt: 'Who created it? Who guards it?' },
  ],
  tradition: [
    { heading: 'The Practice',       prompt: 'Describe the tradition as an outsider would witness it.' },
    { heading: 'When Observed',      prompt: 'Season, occasion, life event.' },
    { heading: 'Participants',       prompt: 'Who takes part? Who is excluded?' },
    { heading: 'Symbols',            prompt: 'Objects, words, foods involved.' },
    { heading: 'Origin',             prompt: 'Why does this tradition exist?' },
    { heading: 'Modern Variants',    prompt: 'How has it changed?' },
  ],
  vehicle: [
    { heading: 'Description',        prompt: 'Appearance and feel.' },
    { heading: 'Propulsion',         prompt: 'Sails, magic, beast, engine?' },
    { heading: 'Crew',               prompt: 'How many, what roles?' },
    { heading: 'Capacity',           prompt: 'Cargo and passengers.' },
    { heading: 'Armament',           prompt: 'Weapons or defenses.' },
    { heading: 'Notable Examples',   prompt: 'Famous ships, mounts, machines.' },
  ],
  conflict: [
    { heading: 'Summary',            prompt: 'In a paragraph: who, what, when, why.' },
    { heading: 'Sides',              prompt: 'Factions and their goals.' },
    { heading: 'Causes',             prompt: 'What set this in motion?' },
    { heading: 'Course of Events',   prompt: 'Key battles, turning points.' },
    { heading: 'Casualties',         prompt: 'Human, material, cultural costs.' },
    { heading: 'Outcome',            prompt: 'How did it end? Or did it?' },
    { heading: 'Aftermath',          prompt: 'What changed because of it?' },
  ],
  deity: [
    { heading: 'Domain',             prompt: 'What aspects of existence do they govern?' },
    { heading: 'Appearance',         prompt: 'How do they manifest, if they do?' },
    { heading: 'Symbol',             prompt: 'The mark of their worship.' },
    { heading: 'Followers',          prompt: 'Who venerates them?' },
    { heading: 'Tenets',             prompt: 'What do they ask of mortals?' },
    { heading: 'Foes',               prompt: 'Rival gods, ancient enemies.' },
    { heading: 'Origin',             prompt: 'Where did they come from?' },
  ],
  history: [
    { heading: 'Era',                prompt: 'When did this take place?' },
    { heading: 'What Happened',      prompt: 'Tell the story.' },
    { heading: 'Key Figures',        prompt: 'Who was there?' },
    { heading: 'Consequences',       prompt: 'How did the world change?' },
    { heading: 'Sources',            prompt: 'Who recorded this, and can they be trusted?' },
  ],
  magic_system: [
    { heading: 'The Source',         prompt: 'Where does magic come from in this world?' },
    { heading: 'Access',             prompt: 'Who can use it? How is it learned?' },
    { heading: 'Cost',               prompt: 'What does magic take from those who wield it?' },
    { heading: 'Rules',              prompt: 'The hard laws. What CANNOT magic do?' },
    { heading: 'Branches',           prompt: 'Schools, traditions, elemental affinities.' },
    { heading: 'Tools',              prompt: 'Wands, runes, focuses, components.' },
    { heading: 'Society',            prompt: 'How does the world treat mages?' },
    { heading: 'History',            prompt: 'When did magic appear? Has it changed?' },
  ],
  note: [
    { heading: 'Notes',              prompt: 'Open scratchpad. Write whatever comes.' },
  ],
};
